module.exports = {
  "Brufen 400mg": "assets/products/product-1.jpg",
  "Paracetamol 500mg": "assets/products/product-2.jpg",
  "Aspirin 500mg": "assets/products/product-3.jpg",
  "Panklav 875mg": "assets/products/product-4.jpg",
  "Amoksicilin 500mg": "assets/products/product-5.jpg",
  "Vitamin C 1000mg": "assets/products/product-6.jpg",
  "Vitamin D3": "assets/products/product-7.jpg",
  "Magnezijum 300mg": "assets/products/product-8.jpg",
  "Omega 3": "assets/products/product-1.jpg",
  "Effaclar Gel": "assets/products/product-2.jpg",
  "Eucerin Hyaluron Filler": "assets/products/product-3.jpg",
  "Pantenol Krema": "assets/products/product-4.jpg",
  "Eucerin pH5 Losion": "assets/products/product-5.jpg",
  "Chicco Baby Kupka": "assets/products/product-6.jpg",
  "Dječiji sirup za imunitet": "assets/products/product-7.jpg",
  "Dječiji vitamin D": "assets/products/product-8.jpg",
  "Baby zaštitna krema": "assets/products/product-1.jpg",
  "Listerine Cool Mint": "assets/products/product-2.jpg",
  "Sensodyne Repair": "assets/products/product-3.jpg",
  "Medicinski sapun": "assets/products/product-4.jpg",
  "Antibakterijski gel": "assets/products/product-5.jpg",
};
