apiVersion: v1
kind: ConfigMap
metadata:
  name: pharmacy-config
  namespace: pharmacy
data:
  MONGO_URI: "mongodb://mongodb-service:27017/pharmacy"
  REDIS_URL: "redis://redis-service:6379"
  CORS_ORIGIN: "http://localhost:30080"
